[toolchain]
channel = "1.85.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
factory = "GGVMhhhYAUuioAw1npbv1NMFBuXs8icgGYQVfjoyEoup"

[programs.devnet]
factory = "GGVMhhhYAUuioAw1npbv1NMFBuXs8icgGYQVfjoyEoup"

[programs.mainnet]
factory = "GGVMhhhYAUuioAw1npbv1NMFBuXs8icgGYQVfjoyEoup"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster="devnet"
wallet = "~/.config/solana/id.json"

[clusters]
localnet = "http://127.0.0.1:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "./tests/spl_token_program.so"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "./tests/mpl_core_program.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "./tests/token_2022_program.so"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "./tests/associated_token_program.so"