[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
factory = "GGVMhhhYAUuioAw1npbv1NMFBuXs8icgGYQVfjoyEoup"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[clusters]
localnet = "http://127.0.0.1:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "./tests/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "./tests/spl_token_program.so"

